# Path: pre_parsed.py
# This file is auto-generated. Do not edit manually.
DATA = {
    "Madeira Drive": 4060,
    "Marine Parade": 2789,
    "Kings Road": 1930,
    "Regency Square": 1915,
    "Old Steine": 1770,
    "Bartholomews": 1615,
    "Western Road": 1336,
    "Church Street": 1333,
    "Kingsway": 1237,
    "King Place": 1185,
    "John Street": 1172,
    "Middle Street": 1025,
    "Ship Street": 1022,
    "North Street": 990,
    "First Avenue": 981,
    "Norfolk Square": 955,
    "Ditchling Road": 953,
    "Wilbury Road": 952,
    "Cannon Place": 949,
    "Lansdowne Place": 945,
    "Dyke Road": 913,
    "Portland Road": 912,
    "Clarence Square": 895,
    "Beaconsfield Road": 888,
    "Brunswick Place": 883,
    "The Drive": 876,
    "Elder Place": 848,
    "Lewes Road": 846,
    "Montpelier Road": 821,
    "Church Road": 803,
    "George Street": 799,
    "New Steine": 797,
    "Holland Road": 761,
    "West Street": 756,
    "Freshfield Road": 754,
    "Spring Gardens": 752,
    "Preston Park Avenue": 739,
    "Springfield Road": 734,
    "Russell Square": 699,
    "Preston Street": 681,
    "Buckingham Road": 670,
    "Islingword Road": 650,
    "Baker Street": 649,
    "Ditchling Rise": 631,
    "Black Lion Street": 628,
    "Boundary Road": 625,
    "Little Preston Street": 608,
    "Morley Street": 608,
    "Goldstone Villas": 607,
    "Regent Street": 606,
    "Station Road": 585,
    "Brunswick Square": 577,
    "Surrenden Road": 568,
    "Bedford Square": 563,
    "Bristol Gate": 560,
    "Bedford Place": 554,
    "New England Street": 552,
    "Second Avenue": 536,
    "Prince Albert Street": 529,
    "Upper North Street": 525,
    "Grand Avenue": 519,
    "Whippingham Road": 519,
    "Blatchington Road": 518,
    "Queens Park Road": 516,
    "Madeira Place": 512,
    "Oriental Place": 497,
    "Kingswood Street": 493,
    "Stone Street": 486,
    "Conway Street": 484,
    "Adelaide Crescent": 480,
    "Castle Street": 477,
    "Palmeira Avenue": 476,
    "St Georges Road": 465,
    "Dorset Gardens": 460,
    "Buckingham Street": 455,
    "Donald Hall Road": 450,
    "Victoria Road": 450,
    "Cromwell Road": 449,
    "Shaftesbury Road": 448,
    "Eastern Road": 445,
    "Hampton Place": 443,
    "Hartington Road": 431,
    "Riley Road": 421,
    "St James's Avenue": 415,
    "Sutherland Road": 410,
    "High Street": 408,
    "Third Avenue": 405,
    "Wellington Road": 405,
    "Elm Grove": 402,
    "Beaconsfield Villas": 398,
    "North Road": 395,
    "Tisbury Road": 391,
    "Preston Drove": 390,
    "Pelham Street": 386,
    "Upper Rock Gardens": 386,
    "Franklin Road": 384,
    "Bristol Gardens": 378,
    "St James Street": 373,
    "Lansdowne Road": 372,
    "Queens Road": 371,
    "Goldstone Road": 368,
    "Bowring Way": 367,
    "Somerhill Road": 365,
    "Richmond Parade": 360,
    "Dyke Road Drive": 359,
    "Walpole Road": 357,
    "St Aubyns": 353,
    "Rose Hill Terrace": 352,
    "York Avenue": 350,
    "Westbourne Place": 349,
    "Addison Road": 348,
    "Fourth Avenue": 345,
    "Waterloo Street": 345,
    "Princes Crescent": 343,
    "Saunders Park View": 343,
    "Bernard Road": 341,
    "Circus Street": 341,
    "Ventnor Villas": 340,
    "Newmarket Road": 337,
    "Hollingbury Road": 336,
    "Ellen Street": 335,
    "Providence Place": 334,
    "Upper Lewes Road": 334,
    "Brunswick Street West": 329,
    "Hova Villas": 329,
    "Nizells Avenue": 324,
    "Union Road": 324,
    "Regent Hill": 320,
    "Albion Street": 319,
    "Duke Street": 318,
    "Sussex Square": 316,
    "Denmark Villas": 315,
    "Eaton Place": 315,
    "Argyle Road": 314,
    "Russell Place": 314,
    "Jubilee Street": 311,
    "Sillwood Street": 311,
    "Kings Esplanade": 307,
    "Bonchurch Road": 306,
    "Paston Place": 305,
    "Robert Street": 304,
    "Roundhill Crescent": 304,
    "West Drive": 304,
    "New Church Road": 303,
    "Marmion Road": 298,
    "Milner Road": 298,
    "Wilbury Avenue": 298,
    "Montpelier Crescent": 297,
    "Goldstone Street": 296,
    "Whitehawk Hill Road": 296,
    "Spring Street": 294,
    "Gladstone Place": 292,
    "Queensbury Mews": 292,
    "Pankhurst Avenue": 291,
    "Wilbury Villas": 290,
    "Shirley Street": 289,
    "Wish Road": 285,
    "White Street": 283,
    "Devonshire Place": 281,
    "Broad Street": 280,
    "Havelock Road": 279,
    "Balfour Road": 278,
    "Inverness Road": 278,
    "Albion Hill": 277,
    "Dewe Road": 277,
    "Stanford Road": 277,
    "Trinity Street": 275,
    "Osborne Road": 272,
    "Selborne Road": 271,
    "Western Street": 271,
    "William Street": 269,
    "Newtown Road": 268,
    "Seafield Road": 266,
    "Warleigh Road": 263,
    "Westbourne Street": 263,
    "Windsor Street": 263,
    "Montgomery Street": 262,
    "Brunswick Terrace": 260,
    "Caledonian Road": 258,
    "Eaton Road": 258,
    "Francis Street": 258,
    "London Road": 258,
    "Palmeira Square": 258,
    "Queen Square": 258,
    "Haddington Street": 257,
    "Vere Road": 257,
    "Shanklin Road": 255,
    "Campbell Road": 254,
    "Walpole Terrace": 254,
    "Norfolk Terrace": 253,
    "Park Crescent Road": 253,
    "Portland Street": 251,
    "Woodside Avenue": 251,
    "Grove Hill": 250,
    "Sudeley Place": 250,
    "Sillwood Road": 247,
    "Chatsworth Road": 245,
    "Tichborne Street": 242,
    "East Street": 241,
    "Craven Road": 240,
    "York Road": 240,
    "Hallyburton Road": 239,
    "Lawrence Road": 239,
    "St Paul's Street": 237,
    "Lansdowne Street": 236,
    "St Martin's Street": 235,
    "Medina Villas": 233,
    "Station Street": 233,
    "Whitecross Street": 232,
    "Bloomsbury Place": 231,
    "Lorna Road": 229,
    "Clarendon Road": 227,
    "Manor Road": 227,
    "Portland Place": 227,
    "Richmond Road": 224,
    "Ashton Rise": 223,
    "Maresfield Road": 222,
    "Westbourne Gardens": 222,
    "Compton Avenue": 221,
    "Southdown Avenue": 219,
    "Lower Rock Gardens": 218,
    "Melbourne Street": 218,
    "Clifton Terrace": 217,
    "Farm Road": 216,
    "Montefiore Road": 216,
    "Hythe Road": 215,
    "Abbey Road": 213,
    "Connaught Road": 211,
    "Harrington Road": 211,
    "Ewhurst Road": 209,
    "Reigate Road": 207,
    "Blaker Street": 205,
    "Clarendon Villas": 205,
    "Cowper Street": 205,
    "Dean Street": 205,
    "Florence Road": 205,
    "St Margaret's Place": 205,
    "Sussex Street": 204,
    "Stroudley Road": 203,
    "Cambridge Road": 202,
    "Whitehawk Road": 202,
    "Palace Place": 201,
    "Viaduct Road": 201,
    "Steyning Road": 200,
    "Coleman Street": 199,
    "Mansfield Road": 198,
    "Sackville Road": 198,
    "Veronica Way": 198,
    "Westbourne Villas": 198,
    "Brunswick Road": 196,
    "Hamilton Road": 194,
    "Preston Road": 194,
    "Clyde Road": 193,
    "Livingstone Road": 191,
    "Princes Road": 191,
    "Vallance Road": 191,
    "Marlborough Street": 190,
    "Wakefield Road": 190,
    "Aberdeen Road": 189,
    "Edinburgh Road": 188,
    "Ladysmith Road": 188,
    "Pelham Square": 187,
    "The Upper Drive": 187,
    "Pembroke Crescent": 186,
    "Walsingham Road": 185,
    "Sudeley Street": 184,
    "School Road": 183,
    "Finsbury Road": 182,
    "Chesham Road": 181,
    "Osborne Villas": 181,
    "Temple Street": 181,
    "Norton Road": 180,
    "Washington Street": 180,
    "Wordsworth Street": 180,
    "Hogarth Road": 179,
    "Manchester Street": 178,
    "Tillstone Street": 178,
    "Brading Road": 176,
    "Prestonville Road": 175,
    "Queens Gardens": 175,
    "Cavendish Place": 174,
    "Chadborn Close": 174,
    "Guildford Road": 174,
    "Hove Park Road": 174,
    "Eaton Gardens": 173,
    "Worcester Villas": 173,
    "Norfolk Road": 172,
    "Vale Road": 172,
    "Rock Street": 171,
    "Highcroft Villas": 170,
    "Hollingbury Park Avenue": 170,
    "Alexandra Villas": 169,
    "Clifton Road": 169,
    "Varndean Drive": 169,
    "Coombe Road": 167,
    "Millers Road": 167,
    "Kemp Street": 165,
    "Park Crescent Terrace": 165,
    "Cobden Road": 164,
    "Queens Place": 164,
    "College Terrace": 163,
    "Rugby Road": 163,
    "Windlesham Gardens": 161,
    "Lowther Road": 160,
    "Montpelier Street": 160,
    "Sheridan Terrace": 160,
    "St Aubyns Road": 160,
    "Grand Junction Road": 159,
    "Stirling Place": 159,
    "Upper St James Street": 159,
    "Gloucester Place": 158,
    "Princes Place": 158,
    "Sandgate Road": 158,
    "Wilbury Gardens": 158,
    "Cleveland Road": 157,
    "St Martins Place": 157,
    "Carlisle Road": 156,
    "St Michael's Place": 156,
    "St Leonard's Road": 155,
    "Blackman Street": 154,
    "Lavender Street": 153,
    "Hanover Terrace": 152,
    "Langdale Gardens": 151,
    "Montpelier Villas": 151,
    "Raphael Road": 151,
    "Sudeley Terrace": 151,
    "Vine Street": 151,
    "Market Street": 150,
    "St Leonard's Avenue": 149,
    "West Hill Road": 149,
    "Hampstead Road": 148,
    "Temple Gardens": 148,
    "Arundel Road": 147,
    "Gerard st": 147,
    "Tamworth Road": 147,
    "West Hill Street": 147,
    "Bear Road": 146,
    "Ewart Street": 146,
    "Shirley Drive": 146,
    "Foundry Street": 144,
    "Southover Street": 144,
    "Ashford Road": 143,
    "Knoyle Road": 143,
    "Rose Hill": 143,
    "Carlton Hill": 141,
    "Port Hall Road": 141,
    "Tidy Street": 141,
    "Upper Gardner Street": 141,
    "Davigdor Road": 140,
    "Gloucester Road": 140,
    "Lucerne Road": 140,
    "Nevill Road": 140,
    "Park Road Rottingdean": 140,
    "Powis Road": 140,
    "Vallance Gardens": 140,
    "Windlesham Road": 140,
    "Edburton Avenue": 139,
    "Grantham Road": 139,
    "Ann Street": 138,
    "Charlotte Street": 138,
    "Gordon Road": 138,
    "Windlesham Avenue": 138,
    "Langdale Road": 137,
    "Margaret Street": 137,
    "Somerhill Avenue": 137,
    "Waldegrave Road": 137,
    "York Hill": 137,
    "Howard Place": 136,
    "Queens Park Terrace": 136,
    "Stanley Road": 136,
    "Vernon Terrace": 136,
    "Bernard Place": 135,
    "Salisbury Road": 135,
    "Tilbury Place": 135,
    "Bath Street": 134,
    "Islingword Street": 134,
    "St Mary Magdalene Street": 134,
    "Eaton Villas": 133,
    "Guildford Street": 133,
    "Park Crescent Place": 133,
    "Queensway": 132,
    "Clifton Hill": 131,
    "St Georges Terrace": 131,
    "Belfast Street": 129,
    "Belle Vue Gardens": 129,
    "Gloucester Street": 129,
    "Hastings Road": 129,
    "Home Road": 129,
    "Steine Street": 129,
    "Regency Road": 128,
    "Chester Terrace": 127,
    "Marlborough Place": 127,
    "Malvern Street": 126,
    "Sydney Street": 126,
    "Wilbury Crescent": 126,
    "North Drive": 125,
    "Connaught Terrace": 124,
    "Dorset Street": 124,
    "St Andrews Road": 124,
    "Brewer Street": 123,
    "Leicester Villas": 123,
    "Over Street": 123,
    "Burlington Street": 122,
    "Newhaven Street": 122,
    "Bates Road": 121,
    "Clarendon Place": 121,
    "Crescent Road": 121,
    "Stafford Road": 121,
    "Brighton Place": 120,
    "Coleridge Street": 120,
    "Dukes Mound": 120,
    "Atlingworth Street": 119,
    "Clifton Street": 119,
    "Loder Road": 119,
    "New Dorset Street": 119,
    "East Drive": 118,
    "Mafeking Road": 118,
    "Powis Square": 118,
    "Chapel Street": 117,
    "Pembroke Avenue": 117,
    "Arundel Street": 116,
    "Highdown Road": 116,
    "Surrey Street": 116,
    "Upper Bedford Street": 116,
    "Albany Villas": 115,
    "Lyndhurst Road": 115,
    "Upper Sudeley Street": 115,
    "Borough Street": 114,
    "Fleet Street": 114,
    "Rutland Gardens": 114,
    "The Droveway": 114,
    "Brunswick Street East": 113,
    "Lewes Crescent": 113,
    "St Nicholas Road": 113,
    "Avondale Road": 112,
    "Berriedale Avenue": 112,
    "Colbourne Road": 112,
    "North Gardens": 112,
    "Titian Road": 112,
    "Turton Close": 112,
    "Bentham Road": 111,
    "Hallett Road": 111,
    "Pevensey Road": 111,
    "Rugby Place": 111,
    "Rushlake Road": 111,
    "Upper Abbey Road": 111,
    "St Luke's Terrace": 110,
    "York Grove": 110,
    "Leopold Road": 109,
    "Montague Place": 109,
    "Richmond Street": 109,
    "Beresford Road": 108,
    "Bristol Place": 108,
    "Montpelier Terrace": 108,
    "Southall Avenue": 108,
    "Tarner Road": 108,
    "Buller Road": 107,
    "Evelyn Terrace": 107,
    "Kimberley Road": 107,
    "Landseer Road": 107,
    "Totland Road": 107,
    "Varndean Road": 106,
    "Princes Terrace": 105,
    "Reynolds Road": 105,
    "College Road": 104,
    "Glebe Villas": 104,
    "Grange Close": 104,
    "Albert Road": 103,
    "Compton Road": 103,
    "Freshfield Way": 103,
    "Hereford Street": 103,
    "Robertson Road": 103,
    "Victoria Street": 103,
    "High Street Rottingdean": 102,
    "Lancaster Road": 102,
    "Roundhill Street": 102,
    "Upper Wellington Road": 102,
    "Chesham Place": 101,
    "Grove Street": 101,
    "Hove Park Villas": 101,
    "De Montfort Road": 100,
    "Duke's Mound": 100,
    "Goldstone Crescent": 100,
    "Hartington Villas": 100,
    "Portland Villas": 100,
    "St Patricks Road": 100,
    "Inwood Crescent": 99,
    "St Helen's Road": 99,
    "Winchester Street": 99,
    "Furze Hill": 98,
    "Marine Square": 98,
    "Rochester Gardens": 98,
    "South Avenue": 98,
    "Coleman Avenue": 97,
    "Frederick Street": 97,
    "Henley Road": 97,
    "Brills Lane": 96,
    "Haddington Close": 96,
    "Newport Street": 96,
    "Richardson Road": 96,
    "Tivoli Crescent": 96,
    "Aymer Road": 95,
    "Kensington Place": 95,
    "Payne Avenue": 95,
    "Sackville Gardens": 95,
    "Hove Street": 94,
    "Regent Row": 94,
    "Rose Hill Close": 94,
    "Hampden Road": 93,
    "Kew Street": 93,
    "Leicester Street": 93,
    "Montreal Road": 93,
    "New Road": 93,
    "Upper Gloucester Road": 93,
    "Carlyle Street": 92,
    "Cuthbert Road": 92,
    "Lower Market Street": 92,
    "St Aubyns South": 92,
    "Islingword Place": 91,
    "Chichester Place": 90,
    "Ivory Place": 90,
    "Melville Road": 90,
    "Pembroke Gardens": 90,
    "Terminus Street": 90,
    "Cheapside": 89,
    "Erroll Road": 89,
    "Maldon Road": 89,
    "Trafalgar Way": 89,
    "Bavant Road": 88,
    "Howard Road": 88,
    "Brooker Street": 87,
    "Centurion Road": 87,
    "Egremont Place": 87,
    "Longridge Avenue": 87,
    "Montague Street": 87,
    "Wilson Avenue": 87,
    "Church Place": 86,
    "Julian Road": 86,
    "Lauriston Road": 86,
    "York Villas": 86,
    "Agnes Street": 85,
    "Chapel Terrace": 85,
    "Coronation Street": 85,
    "Marine View": 85,
    "Southampton Street": 85,
    "Upper Market Street": 85,
    "Wellington Street": 85,
    "Hanover Street": 84,
    "Redvers Road": 84,
    "Belgrave Place": 83,
    "Bond Street": 83,
    "Braemore Road": 83,
    "Coldean Lane": 83,
    "Goodwood Way": 83,
    "Saxon Road": 83,
    "St Marks Street": 83,
    "York Place": 83,
    "Cavendish Street": 82,
    "College Place": 82,
    "Percival Terrace": 82,
    "Portland Avenue": 82,
    "Down Terrace": 81,
    "Franklin Street": 81,
    "Herbert Road": 81,
    "Leighton Road": 81,
    "Milton Road": 81,
    "Ardingly Street": 80,
    "Clermont Terrace": 80,
    "Hendon Street": 80,
    "Hove Place": 80,
    "Coventry Street": 79,
    "Grafton Street": 79,
    "Grange Road": 79,
    "Pavilion Street": 79,
    "Princes Avenue": 79,
    "Tenantry Down Road": 79,
    "Bennett Road": 78,
    "Kingsbury Road": 78,
    "Lincoln Street": 78,
    "Pool Valley": 78,
    "Bolsover Road": 77,
    "Modena Road": 77,
    "Mortimer Road": 77,
    "Old Shoreham Road": 77,
    "St Peters Street": 77,
    "Welbeck Avenue": 77,
    "Bromley Road": 76,
    "Hampton Street": 76,
    "Medina Terrace": 76,
    "Park Street": 76,
    "Prinsep Road": 76,
    "Stanford Avenue": 76,
    "The Green": 76,
    "Wharf Road": 76,
    "Alfred Road": 75,
    "Natal Road": 75,
    "Trafalgar Street": 75,
    "Bloomsbury Street": 74,
    "Dawson Terrace": 74,
    "Dover Road": 74,
    "St Heliers Avenue": 74,
    "Stoneham Road": 74,
    "Clayton Road": 73,
    "Frith Road": 73,
    "Moulsecoomb Way": 73,
    "Norway Street": 73,
    "Queens Park Rise": 73,
    "Carlyle Avenue": 72,
    "Richmond Place": 72,
    "Cowfold Road": 71,
    "D'Aubigny Road": 71,
    "Harrington Villas": 71,
    "Osmond Road": 71,
    "St Georges Place": 71,
    "Frederick Place": 70,
    "Marlow Road": 70,
    "Terminus Place": 70,
    "Ethel Street": 69,
    "Great College Street": 69,
    "Norman Road": 69,
    "North Place": 69,
    "Chichester Terrace": 68,
    "Denmark Terrace": 68,
    "Exeter Street": 68,
    "Hawkhurst Road": 68,
    "Kingsmere": 68,
    "Oxford Place": 68,
    "Tennis Road": 68,
    "Bristol Street": 67,
    "Buxton Road": 67,
    "Chanctonbury Road": 67,
    "Dudley Road": 67,
    "Hillside": 67,
    "Onslow Road": 67,
    "Park Road": 67,
    "Seville Street": 67,
    "Southdown Road": 67,
    "Freehold Terrace": 66,
    "Baden Road": 65,
    "Byron Street": 65,
    "Cissbury Road": 65,
    "Clermont Road": 65,
    "Essex Street": 65,
    "Hollingdean Terrace": 65,
    "Queensdown School Road": 65,
    "Sandown Road": 65,
    "Gardner Street": 64,
    "Goldstone Lane": 64,
    "Powis Grove": 64,
    "Rutland Road": 64,
    "St Johns Place": 64,
    "Upper Hamilton Road": 64,
    "Belgrave Street": 63,
    "Fonthill Road": 63,
    "Montpelier Place": 63,
    "John Street/Edward Street": 62,
    "Lorne Road": 62,
    "Brittany Road": 61,
    "Fairlight Place": 61,
    "Rock Grove": 61,
    "Arundel Terrace": 60,
    "Ashurst Road": 60,
    "Chesham Street": 60,
    "Hollingbury Terrace": 60,
    "Marine Avenue": 60,
    "Meeting House Lane": 60,
    "Newick Road": 60,
    "Phoenix Rise": 60,
    "Rochester Street": 60,
    "Roedale Road": 60,
    "Selborne Place": 60,
    "Granville Road": 59,
    "Howard Terrace": 59,
    "Kingsley Road": 59,
    "Manor Hill": 59,
    "Railway Street": 59,
    "St Johns Road": 59,
    "Shakespeare Street": 58,
    "Chailey Road": 57,
    "Palmeira Place": 57,
    "Tower Road": 57,
    "West Hill Place": 57,
    "Wyndham Street": 57,
    "Ranelagh Villas": 56,
    "Somerset Street": 56,
    "Undercliff Walk": 56,
    "Arnold Street": 55,
    "Bembridge Street": 55,
    "Bevendean Road": 55,
    "Russell Crescent": 55,
    "Saltdean Park Road": 55,
    "Steine Gardens": 55,
    "College Street": 54,
    "Cornwall Gardens": 54,
    "Cumberland Road": 54,
    "Kingsthorpe Road": 54,
    "Rothbury Road": 54,
    "Russell Road": 54,
    "Whichelo Place": 54,
    "Oxford Court": 53,
    "Poynter Road": 53,
    "Quebec Street": 53,
    "Shirley Road": 53,
    "Tivoli Crescent North": 53,
    "Castle Square": 52,
    "Ferndale Road": 52,
    "Freshfield Place": 52,
    "Matlock Road": 52,
    "Mount Pleasant": 52,
    "Radinden Manor Road": 52,
    "Shaftesbury Place": 52,
    "Crayford Road": 51,
    "Cross Street": 51,
    "Hartington Place": 51,
    "St Marys Place": 51,
    "Waverley Crescent": 51,
    "Arundel Place": 50,
    "Cheltenham Place": 50,
    "Elmore Road": 50,
    "Jew Street": 50,
    "Port Hall Place": 50,
    "Roman Road": 50,
    "Seaford Road": 50,
    "Surrenden Crescent": 50,
    "Conway Place": 49,
    "Jesmond Road": 49,
    "Little East Street": 49,
    "Thames Close": 49,
    "Bigwood Avenue": 48,
    "Goldsmid Road": 48,
    "Jersey Street": 48,
    "YARDLEY STREET": 48,
    "Hollingdean Street": 47,
    "Jevington Drive": 47,
    "Kings Gardens": 47,
    "Park Crescent": 47,
    "Picton Street": 47,
    "The Highway": 47,
    "Tilgate Close": 47,
    "Amesbury Crescent": 46,
    "Boston Street": 46,
    "Chalky Road": 46,
    "Clifton Place": 46,
    "Glendale Road": 46,
    "Ingram Crescent West": 46,
    "Park View Road": 46,
    "St Leonards Road": 46,
    "Sussex Road": 46,
    "Kensington Street": 45,
    "Lansdowne Square": 45,
    "Little Western Street": 45,
    "Powis Villas": 45,
    "Slinfold Close": 45,
    "Stanley Street": 45,
    "Staplefield Drive": 45,
    "Bute Street": 44,
    "Hartington Terrace": 44,
    "Hughes Road": 44,
    "St Keyna Avenue": 44,
    "Toronto Terrace": 44,
    "Windmill Street": 44,
    "Belmont": 43,
    "Eastbourne Road": 43,
    "Hill Brow": 43,
    "Ingram Crescent East": 43,
    "Wayland Avenue": 43,
    "Canning Street": 42,
    "Prince Regent Close": 42,
    "South Street": 42,
    "St Luke's Road": 42,
    "Belton Road": 41,
    "Dorothy Road": 41,
    "Lucraft Road": 41,
    "Ryde Road": 41,
    "Station Approach": 41,
    "Alice Street": 40,
    "Birdham Road": 40,
    "Eastern Terrace": 40,
    "Grant Street": 40,
    "Kendal Road": 40,
    "Linton Road": 40,
    "Silverdale Road": 40,
    "Suffolk Street": 40,
    "Arthur Street": 39,
    "Belmont Street": 39,
    "Florence Avenue": 39,
    "Loder Place": 39,
    "Lynton Street": 39,
    "Newmarket Terrace": 39,
    "Whippingham Street": 39,
    "Derek Avenue": 38,
    "Grand Parade": 38,
    "London Terrace": 38,
    "Oxford Street": 38,
    "Park Hill": 38,
    "Surrenden Park": 38,
    "Woodhouse Road": 38,
    "Baxter Street": 37,
    "Charles Street": 37,
    "Normanton Street": 37,
    "Roedean Road": 37,
    "Woodruff Avenue": 37,
    "Denmark Road": 36,
    "Freshfield Street": 36,
    "Halland Road": 36,
    "Old London Road": 36,
    "Plumpton Road": 36,
    "Royal Crescent Mews": 36,
    "Southwater Close": 36,
    "Alpine Road": 35,
    "Chatham Place": 35,
    "Eastern Place": 35,
    "Hangleton Road": 35,
    "Sandhurst Avenue": 35,
    "Brambledean Road": 34,
    "Brigden Street": 34,
    "Crown Street": 34,
    "Egginton Road": 34,
    "Kingsbury Street": 34,
    "Bedford Street": 33,
    "Carden Avenue": 33,
    "Court Farm Road": 33,
    "Holland Street": 33,
    "Lincoln Cottages": 33,
    "Mighell Street": 33,
    "Nutley Avenue": 33,
    "Rookery Close": 33,
    "Surrenden Holt": 33,
    "Valley Road": 33,
    "Caburn Road": 32,
    "Edward Street": 32,
    "Luther Street": 32,
    "Princes Square": 32,
    "Saunders Park Rise": 32,
    "Selsfield Drive": 32,
    "Tongdean Road": 32,
    "Upper Hollingdean Road": 32,
    "withdean rise": 32,
    "Wolstonbury Road": 32,
    "Barcombe Road": 31,
    "Glendor Road": 31,
    "Lennox Street": 31,
    "Stonery Road": 31,
    "The Causeway": 31,
    "College Gardens": 30,
    "Godwin Road": 30,
    "Ruskin Road": 30,
    "The Drove": 30,
    "The Martlet": 30,
    "Tilbury Way": 30,
    "Appledore Road": 29,
    "Fitzherbert Drive": 29,
    "Manor Place": 29,
    "May Road": 29,
    "Mayo Road": 29,
    "Molesworth Street": 29,
    "New England Road": 29,
    "Semley Road": 29,
    "Whiteway Lane": 29,
    "Burton Villas": 28,
    "Draxmont Way": 28,
    "Merlin close": 28,
    "St Leonard's Gardens": 28,
    "St Michaels Road": 28,
    "Withdean Road": 28,
    "Colbourne Avenue": 27,
    "De Courcel Road": 27,
    "Egginton Close": 27,
    "Lennox Road": 27,
    "Nesbitt Road": 27,
    "Pavilion Parade": 27,
    "Port Hall Avenue": 27,
    "Scotland Street": 27,
    "Beacon Close": 26,
    "Cranbourne Street": 26,
    "Hodshrove Road": 26,
    "Manor Way": 26,
    "Margery Road": 26,
    "Middleton Rise": 26,
    "Port Hall Street": 26,
    "Roundhill Road": 26,
    "Tamplin Terrace": 26,
    "Beatty Avenue": 25,
    "Camden Street": 25,
    "Camelford Street": 25,
    "Canfield Road": 25,
    "Wentworth Street": 25,
    "Wolseley Road": 25,
    "Dallington Road": 24,
    "Davey Drive": 24,
    "Hill Drive": 24,
    "Norfolk Place": 24,
    "The Cliff": 24,
    "Newark Place": 23,
    "Royal Crescent": 23,
    "Tandridge Road": 23,
    "Wincombe Road": 23,
    "Withdean Crescent": 23,
    "Ashdown Road": 22,
    "Clarendon Terrace": 22,
    "Cranmer Avenue": 22,
    "Crowhurst Road": 22,
    "Marshall's Row": 22,
    "Nevill Avenue": 22,
    "Stonehurst Court": 22,
    "Arlington Crescent": 21,
    "Benett Drive": 21,
    "Buckler Street": 21,
    "Livingstone Street": 21,
    "Meadow View": 21,
    "Orchard Road": 21,
    "Stonecross Road": 21,
    "Symbister Road": 21,
    "Victoria Place": 21,
    "Bishops Road": 20,
    "Bramble Way": 20,
    "Florence Place": 20,
    "Gladys Road": 20,
    "Grosvenor Street": 20,
    "Scarborough Road": 20,
    "Seymour Street": 20,
    "Swanborough Drive": 20,
    "Tavistock Down": 20,
    "Ashburnham Drive": 19,
    "Bristol Road": 19,
    "Carisbrooke Road": 19,
    "Drove Road": 19,
    "Elm Drive": 19,
    "Hove Park Way": 19,
    "Hove Street South": 19,
    "Links Road": 19,
    "Mainstone Road": 19,
    "Middleton Avenue": 19,
    "Milnthorpe Road": 19,
    "Park Road Terrace": 19,
    "The Avenue": 19,
    "Arundel Drive West": 18,
    "Crescent Place": 18,
    "Lover's Walk": 18,
    "Medina Place": 18,
    "Tongdean Avenue": 18,
    "Western Terrace": 18,
    "Withdean Avenue": 18,
    "Withyham Avenue": 18,
    "Bexhill Road": 17,
    "Buckingham Place": 17,
    "Carlton Terrace": 17,
    "Dawlish Close": 17,
    "Dorset Place": 17,
    "Dyke Road Avenue": 17,
    "Glynde Road": 17,
    "Lyon Close": 17,
    "Silverdale Avenue": 17,
    "Tongdean Lane": 17,
    "Benfield Way": 16,
    "Hardwick Road": 16,
    "Manor Gardens": 16,
    "Nyetimber Hill": 16,
    "Reeves Hill": 16,
    "Romany Close": 16,
    "Warren Way": 16,
    "West Way": 16,
    "Abinger Road": 15,
    "Bevendean Crescent": 15,
    "Bond Street Row": 15,
    "Graham Avenue": 15,
    "Mornington Crescent": 15,
    "Orpen Road": 15,
    "South Road": 15,
    "Tivoli Road": 15,
    "Westergate Road": 15,
    "Boyces Street": 14,
    "Chelston Avenue": 14,
    "Dyke Road Place": 14,
    "Hollingbury Place": 14,
    "Hove Base": 14,
    "Isabel Crescent": 14,
    "Jackson Street": 14,
    "Ladies Mile Road": 14,
    "Medmerry Hill": 14,
    "Princes Street": 14,
    "Ditchling Gardens": 13,
    "Drove Crescent": 13,
    "Friar Crescent": 13,
    "Friar Road": 13,
    "Hangleton Way": 13,
    "Ingham Drive": 13,
    "Parham Close": 13,
    "Park Avenue": 13,
    "Rigden Road": 13,
    "Scott Road": 13,
    "The Crescent": 13,
    "The Crestway": 13,
    "Warmdene Avenue": 13,
    "Amherst Crescent": 12,
    "Attree Drive": 12,
    "Bampfield Street": 12,
    "Denton Drive": 12,
    "Donkey Mews": 12,
    "Farm Yard": 12,
    "Hadlow Close": 12,
    "Leahurst Court Road": 12,
    "Meadow Close": 12,
    "Middle Road": 12,
    "Mile Oak Road": 12,
    "Parkmore Terrace": 12,
    "Whittingehame Gardens": 12,
    "Church Hill": 11,
    "Cliff Road": 11,
    "Cromwell Street": 11,
    "Norfolk Street": 11,
    "Orchard Avenue": 11,
    "Ringmer Drive": 11,
    "Robin Dene": 11,
    "Thorndean Road": 11,
    "Tredcroft Road": 11,
    "Warren Road": 11,
    "Barnfield Gardens": 10,
    "Benett Avenue": 10,
    "Birling Close": 10,
    "Blenheim Place": 10,
    "Bread Street": 10,
    "Eastbrook Road": 10,
    "Hertford Road": 10,
    "Hollingbury Crescent": 10,
    "Locks Crescent": 10,
    "Lullington Avenue": 10,
    "Mallory Road": 10,
    "Shelley Road": 10,
    "Braybon Avenue": 9,
    "Carden Crescent": 9,
    "Dean Court Road": 9,
    "Downside": 9,
    "Gladstone Road": 9,
    "Haig Avenue": 9,
    "Hollingbury Rise": 9,
    "Langley Crescent": 9,
    "Lloyd Road": 9,
    "Locks Hill": 9,
    "Lustrells Vale": 9,
    "Martha Gunn Road": 9,
    "Roundway": 9,
    "Varndean Gardens": 9,
    "Wickhurst Close": 9,
    "Wickhurst Road": 9,
    "Barnet Way": 8,
    "Barrowfield Drive": 8,
    "Bazehill Road": 8,
    "Canfield Close": 8,
    "Canterbury Drive": 8,
    "County Oak Avenue": 8,
    "Hardwick Way": 8,
    "Highfields": 8,
    "Holland Mews": 8,
    "Monument View": 8,
    "Northease Drive": 8,
    "Ridge View": 8,
    "St Peters Road": 8,
    "Stonery Close": 8,
    "Weald Avenue": 8,
    "Aldrington Avenue": 7,
    "Beaufort Terrace": 7,
    "Cliff Approach": 7,
    "DOWNLAND COURT": 7,
    "Eastergate Road": 7,
    "Falmer Road": 7,
    "Firle Road": 7,
    "Foredown Drive": 7,
    "Holmes Avenue": 7,
    "King Street": 7,
    "Selham Drive": 7,
    "Stanmer Villas": 7,
    "Terminus Road": 7,
    "Thompson Road": 7,
    "Upper Park Place": 7,
    "Varndean Holt": 7,
    "Woodlands": 7,
    "Arundel Drive East": 6,
    "Bolney Road": 6,
    "Borrow King Close": 6,
    "Cowley Drive": 6,
    "CRESPIN WAY": 6,
    "Elm Road": 6,
    "Elrington Road": 6,
    "Malthouse Lane": 6,
    "Newlands Road": 6,
    "Park Close": 6,
    "Portfield Avenue": 6,
    "Ringmer Road": 6,
    "Saltdean Drive": 6,
    "St Peters Place": 6,
    "Willingdon Road": 6,
    "Windlesham Close": 6,
    "Windmill Terrace": 6,
    "Applesham Avenue": 5,
    "Buckley Close": 5,
    "Carden Hill": 5,
    "Chichester Drive East": 5,
    "Elms Lea Avenue": 5,
    "Falmer Gardens": 5,
    "Lincoln Road": 5,
    "Maple Gardens": 5,
    "Melrose Avenue": 5,
    "Milcote Avenue": 5,
    "Mount Zion Place": 5,
    "Norfolk Buildings": 5,
    "Orange Row": 5,
    "Oxford Court Car Park": 5,
    "Phoenix Place": 5,
    "Poplar Close": 5,
    "Redcross Street": 5,
    "Rusper Road": 5,
    "The Charltons": 5,
    "Vernon Gardens": 5,
    "Wilmington Parade": 5,
    "Amberley Drive": 4,
    "Beech Grove": 4,
    "Caisters Close": 4,
    "Chalfont Drive": 4,
    "Gardener Street": 4,
    "Harmsworth Crescent": 4,
    "Harrington Place": 4,
    "Hazeldene Meads": 4,
    "Highbrook Close": 4,
    "Hornby Road": 4,
    "Junction Road": 4,
    "Kenton Road": 4,
    "Kenwards": 4,
    "Kestrel Close": 4,
    "Madehurst Close": 4,
    "Manor Close": 4,
    "Nanson Road": 4,
    "Oakdene Crescent": 4,
    "Saunders Hill": 4,
    "Shortgate Road": 4,
    "Southdown Place": 4,
    "St Josephs Close": 4,
    "Stapley Road": 4,
    "Stonecroft Close": 4,
    "Sullington Close": 4,
    "Swanborough Place": 4,
    "Tenantry Road": 4,
    "Trafalgar Road": 4,
    "Waldron Avenue": 4,
    "Wheatfield Way": 4,
    "Woodland Avenue": 4,
    "Auckland Drive": 3,
    "Bellingham Crescent": 3,
    "Deanway": 3,
    "Downsview Road": 3,
    "Fairfield Gardens": 3,
    "Forest Road": 3,
    "Foxdown Road": 3,
    "Glastonbury Road": 3,
    "Highlands Road": 3,
    "Hillcrest": 3,
    "Hollingdean Road": 3,
    "Horton Road": 3,
    "Hurst Crescent": 3,
    "Linchmere Avenue": 3,
    "Manor Paddock": 3,
    "Martin Road": 3,
    "Mulberry Close": 3,
    "Olive Road": 3,
    "Orchard Gardens": 3,
    "Pavilion Buildings": 3,
    "Peacock Lane": 3,
    "Rosebery Avenue": 3,
    "Selham Close": 3,
    "Shelldale Road": 3,
    "Shirley Avenue": 3,
    "St Georges Mews": 3,
    "Surrenden Close": 3,
    "Sussex Place": 3,
    "Torcross Close": 3,
    "Valley Drive": 3,
    "Vicarage Lane": 3,
    "Walton Bank": 3,
    "Warmdene Close": 3,
    "Widdicombe Way": 3,
    "Wigmore Close": 3,
    "Woodland Parade": 3,
    "Zion Gardens": 3,
    "ALDRICH CLOSE": 2,
    "Applesham Way": 2,
    "Barn Rise": 2,
    "Barry Walk": 2,
    "Batemans Road": 2,
    "Beaconsfield Parade": 2,
    "Beechers Road": 2,
    "Brentwood Road": 2,
    "Brooker Place": 2,
    "Broomfield Drive": 2,
    "Crawley Road": 2,
    "Crescent Drive North": 2,
    "Cuckmere Way": 2,
    "Curwen Place": 2,
    "Dale Avenue": 2,
    "Dennis Hobden Close": 2,
    "Dyke Close": 2,
    "Eridge Road": 2,
    "Findon Road": 2,
    "Founthill Avenue": 2,
    "Frant Road": 2,
    "Friar Walk": 2,
    "Friston Close": 2,
    "Fulmar Close": 2,
    "Ghyllside": 2,
    "Kipling Avenue": 2,
    "knoll close": 2,
    "Laburnum Avenue": 2,
    "Laughton Road": 2,
    "Lewes Street": 2,
    "Manor Crescent": 2,
    "Manor Green": 2,
    "McWilliam Road": 2,
    "Mill Rise": 2,
    "Morecambe Road": 2,
    "Moyne Close": 2,
    "Norwich Drive": 2,
    "Overhill Way": 2,
    "Peel Road": 2,
    "Poplar Avenue": 2,
    "Poynings Drive": 2,
    "Rock Place": 2,
    "Rowan Avenue": 2,
    "Rudyard Road": 2,
    "Rushlake Close": 2,
    "Selba Drive": 2,
    "Stanford Close": 2,
    "Sunnydale Avenue": 2,
    "The Approach": 2,
    "The Crossway": 2,
    "The Gardens": 2,
    "The Paddock": 2,
    "The Ridgway": 2,
    "Vale Gardens": 2,
    "Varndean Close": 2,
    "Warmdene Road": 2,
    "Wayfield Avenue": 2,
    "Westdene Drive": 2,
    "Whitehawk Crecent": 2,
    "Withdean Court Avenue": 2,
    "WOLVERSTONE DRIVE": 2,
    "Woodland Drive": 2,
    "Adams Close": 1,
    "Albourne Close": 1,
    "Balsdean Road": 1,
    "Bodiam Avenue": 1,
    "Bramber Avenue": 1,
    "Brownleaf Road": 1,
    "Burstead Close": 1,
    "Carden Close": 1,
    "channel view road": 1,
    "Chiltington Way": 1,
    "COURT ORD ROAD": 1,
    "Crescent Drive South": 1,
    "Crossbush Road": 1,
    "Dale View": 1,
    "Downs Terrace": 1,
    "Easthill Drive": 1,
    "Eastwick Close": 1,
    "Eldred Avenue": 1,
    "Elizabeth Avenue": 1,
    "Elsted Crescent": 1,
    "Fairlie Gardens": 1,
    "Farman Street": 1,
    "Findon Close": 1,
    "Fitch Drive": 1,
    "Flimwell Close": 1,
    "Foredown Road": 1,
    "Glyndebourne Avenue": 1,
    "Goldstone Close": 1,
    "Graham Close": 1,
    "Graham Crescent": 1,
    "Greenfield Crescent": 1,
    "Greyfriars": 1,
    "Hamilton Close": 1,
    "Hangleton Gardens": 1,
    "Hayes Close": 1,
    "Haywards Road": 1,
    "HEATH HILL AVENUE": 1,
    "Helena Road": 1,
    "Highview Avenue North": 1,
    "Highway Close": 1,
    "Hill Top": 1,
    "King Alfred": 1,
    "King George VI Drive": 1,
    "Leybourne Road": 1,
    "Lucerne Close": 1,
    "Lynwood Road": 1,
    "Mackie Avenue": 1,
    "Major Close": 1,
    "Marlborough Mews": 1,
    "May Tree Walk": 1,
    "Meadway Crescent": 1,
    "Mill Lane": 1,
    "Millfield Cottages": 1,
    "Millyard Crescent": 1,
    "Nevill Gardens": 1,
    "New Barn Road": 1,
    "Northease Close": 1,
    "Overhill Gardens": 1,
    "Park Road Coldean": 1,
    "Playden Close": 1,
    "Plymouth Avenue": 1,
    "Popes Folly": 1,
    "Queens Road Quadrant": 1,
    "Roedean Way": 1,
    "Rosedene Close": 1,
    "Rotherfield Crescent": 1,
    "Sandyhils Avenue": 1,
    "School Lane": 1,
    "Shelldale Crescent": 1,
    "Sherbourne Close": 1,
    "Sherbourne Road": 1,
    "Southmount": 1,
    "Steine Lane": 1,
    "Stevenson Road": 1,
    "Steyning Avenue": 1,
    "Sutton Close": 1,
    "Tangmere Road": 1,
    "The Broadway": 1,
    "The Byway": 1,
    "The Deneway": 1,
    "The Drive/Eaton Road": 1,
    "The Heights": 1,
    "Tudor Close": 1,
    "Twyford Road": 1,
    "Upper Bevendean Avenue": 1,
    "Vine Cross Road": 1,
    "Whitehawk Close": 1,
    "Whitehawk Way": 1,
    "Whitethorn Drive": 1,
    "Wicklands Avenue": 1,
    "Wilmington Way": 1,
    "Winfield Close": 1,
    "Winston Road": 1,
    "Wiston Road": 1,
    "Woburn Place": 1,
    "Woodside": 1
}
